[package]
name = "muetl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kameo = "0.18.0"
kameo_actors = "0.3.0"
