[package]
name = "muetl-tasks"
version = "0.1.0"
edition = "2021"
description = "Common utility tasks for muetl (sources, nodes, sinks)"

[dependencies]
muetl = { path = "../.." }
async-trait = "0.1.89"
tokio = { version = "1.48.0", features = ["full", "sync"] }
tracing = "0.1.43"
